// 三阶段/vue/vue单文件组件/src/pages/Wechat.vue
<template>
  <div>
    <Header color="green">微信</Header>
    <Search />
    <Panel />
  </div>
</template>
<script>
import Header from "../model/Header.vue";
import Search from "../model/Search.vue";
import Panel from "../model/Panel.vue";
export default {
  components: {
    Header,
    Search,
    Panel
  }
};
</script>

// 三阶段/react/day04/dva-app/src/routes/Wechat.js
// import React from 'react';
import Header from '../components/Header'
import Search from '../components/Search'
import Panel from '../components/Panel'
import Tabbar from '../components/Tabbar'


function Wechat() {
  return (
    <div >
      <Header />
      <Search />
      <Panel />
      <Tabbar />
    </div>
  );
}

export default Wechat;
