// 三阶段/react/day05/2、redux模块化开发/dva-app/src/routes/Wechat.js
// import React from 'react';
import Header from '../components/Header'
import Search from '../components/Search'
import Panel from '../components/Panel'
import Tabbar from '../components/Tabbar'
import Gallery from '../components/Gallery'


function Wechat() {
  return (
    <div >
      <Header />
      <Search />
      <Panel />
      <Tabbar />
      <Gallery />
    </div>
  );
}

export default Wechat;

// 三阶段/vue/vue单文件组件 结合vuex/src/pages/Wechat.vue
<template>
  <div>
    <Header color="green">微信</Header>
    <Search />
    <Panel />
    <Gallery />
    <Toast />
  </div>
</template>
<script>
import Header from "../model/Header.vue";
import Search from "../model/Search.vue";
import Panel from "../model/Panel.vue";
import Gallery from "../model/Gallery.vue";
import Toast from "../model/Toast.vue";
export default {
  components: {
    Header,
    Search,
    Panel,
    Gallery,
    Toast
  }
};
</script>
